version: "3"
build: .
services:
  python:
    image: "python:3.11.9"
    hostname: python-server
    container_name: python3
    volumes: . :/server
    working_dir: /server
    networks:
      - fontnet
      - backnet
    depends_on:
      - redis
    environment:
      - FASTAPI_APP = core/api.py
      - FASTAPI_ENV = development
    command: ['python3', 'install', "uvicorn", "fastapi[all]", "redis-py", "websocket", 'starlette']

  redis:
    image: "redis:latest"
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    restart: alawys
    networks:
      - backnet
    volumes:
      - data:/data
      - ./databasetool/redis-service.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  vue:
    image: "nodejs.latest"
    build: 
      context: ./
      dockerfile: /view/docker/Dockerfile

    prots:
      - '8080:8080'
    depends_on:
      - node
    working_dir:
      /server/view
    
    networks:
      - fondnet

    volumes:
      - /view:/view
  
  node:
    image: "nginx:latest"
    working_dir: /server/view
    command: npm install

networks:
  fondnet:
  backnet:
  
volumes:
  data:

command: ['python3', "/server/start.py"]