
services:
  fastapi:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: RemoteControl-Server
    volumes:
      - ./core:/Server/core
      - ./databasetool:/Server/databasetool
      - ./datamodel:/Server/datamodel
      - ./logs:/Server/logs
      - ./projectdesposetool:/Server/projectdesposetool
      - ./init.py:/Server/init.py
      - ./start.py:/Server/start.py
      - ./config.xml:/Server/config.xml
    ports:
      - 8000:8000/tcp
    depends_on:
      - redis
    networks:
      frontnet:
      backnet:

  redis:
    image: "redis:latest"
    container_name: RemoteControl-Database
    ports:
      - 6379:6379/tcp
    networks:
      backnet:
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - data:/data
      - ./databasetool/redis-service.conf:/usr/local/etc/redis/redis.conf

  vue:
    image: "remotecontrol-view"
    container_name: RemoteControl-View
    depends_on:
      - fastapi
    ports:
      - 8080:8080/tcp
    volumes:
      - ../view:/view
    networks:
      frontnet:
      
volumes:
  data:

networks:
  frontnet:
    driver: bridge
  backnet:
    driver: bridge
